name: Test Workflow

on:
  push:
    branches: [develop, main]

  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: ""

      - name: Install deps
        run: yarn install

      - name: Run tests
        run: yarn test